### ISSUE TITLE
l7805c2 voltage regulating overheating when connected to 24v power supply

### ISSUE THREAD

**Issue by Sferatos12** [makerbase-mks/MKS-DLC#11]
l7805c2 voltage regulator overheating when connected to 24v power supply
also the TFT35 cnc keeps disconecting from the board....

**Comment by DirtyEngineer** [comment]
The board is designed for a 12v power supply not a 24v.

**Comment by sferatos** [comment]
Please see #4 they claim can support 24 v, that is the reason i bought it...

**Comment by mks-viva** [comment]
Yes, MKS DLC support DC24V, you can refer to datasheet
[L7805CD2T-TR datasheet.pdf](https://github.com/makerbase-mks/MKS-DLC/files/6098877/L7805CD2T-TR.datasheet.pdf)
![image](https://user-images.githubusercontent.com/16629551/110273549-cb5e1880-8007-11eb-8ac4-806f8b49c456.png)
