### ISSUE TITLE
What are the possible J2, J6 and J12 (step mode) pinouts for TMC2208?

### ISSUE THREAD

**Issue by asarmelin** [makerbase-mks/MKS-DLC#18]
What are the possible J2, J6 and J12 (step mode) jumpers pinouts for TMC2208?

1 | 2 | 3 || step mode
--| --| --|| --
1 | 0 | 0 || 2 step
0 | 1 | 0 || 4 step
0 | 0 | 0 || 8 step
1 | 1 | 0 || 16 step

Is this table correct?

**Comment by mks-viva** [comment]
![image](https://user-images.githubusercontent.com/16629551/130774690-9a605372-555b-47cd-bc52-a596576637a9.png)
