### ISSUE TITLE
Data sheet is needed

### ISSUE THREAD

**Issue by Erick010** [makerbase-mks/MKS-DLC#2]
#1 
Please, publish a complete data sheet of the MKS-DLC v2.0, which includes connection diagrams, maximum values and configurations, as there are for the other MKS plates, the data sheet contains information necessary to solve problems that arise when using it with hardware other than the recommended one or try to use it differently.

Thanks in advance

**Comment by makerbase-mks** [comment]
@Erick010
We have open sourced most of the hardware, including MKS DLC and so on

**Comment by ribbles** [comment]
Please don't close this @makerbase-mks - no data sheet has been provided.
