### ISSUE TITLE
No action from TFT35

### ISSUE THREAD

**Issue by killrob** [makerbase-mks/MKS-DLC#3]
Hi, i can engrave normally if the MB is connected to PC but i can't in standalone.
Offline neither movements of axes works

**Comment by makerbase-mks** [comment]
Hi! Can your TFT35 and DLC motherboard communicate normally? I think you should check the TFT35 baud rate to match the DLC motherboard.

**Comment by killrob** [comment]
ok i will check it but i installed the laser firmware from this site

**Comment by killrob** [comment]
Ok i've set the correct baud rate and now it works, thank you

**Comment by makerbase-mks** [comment]
OK! I will close this problem.
