### ISSUE TITLE
Wiring limit switches of the MKS - DLC 

### ISSUE THREAD

**Issue by mldmld68** [makerbase-mks/MKS-DLC#9]
Hi

Where could I find a documentation about the limit switches of the MKS-DLC ?
Do the configuration to use is the same as : https://github.com/gnea/grbl/wiki/Wiring-Limit-Switches ?

In particular, do one need to add filtering with the MKS - DLC ? Or  do the MKS-DLC already have filtering features ? 

AFAIU, one need to enter $5=1 to use Normaly Closed switches.
Thank you

**Comment by mks-viva** [comment]
Hi! MKS DLC compatible with GRBL

**Comment by UnleashSpirit** [comment]
It works for me, I use basic limit switches (like 3D printer) wired in a NO way. On the board wire them in the two lower pins, G&S, of the 3 pins connectors
My $5 is at 0.

**Comment by mldmld68** [comment]
Thank you,  so no need of capacitors and resistors.
I would consider NC option instead.

**Comment by mks-viva** [comment]
@UnleashSpirit 
Thank you!

@mldmld68
It is usually triggered by S G. If you actually test it and it works, then you can use.

**Comment by jcmcharro** [comment]
Watch out some 3D printer switches come with the pinout in reverse the way you may be connecting S on V and V on S => shortcircuit V-GND when closing the switch...
If you Makerbase board restarts when pressing the switch just exchange White and Red wires (S and V).
Best regards
